### PR TITLE
[#39] Upgraded to std@0.100.0 to work with deno 1.11.4.

### PR DESCRIPTION
**Pull request by eclosson**
# Issue

Test suite is failing on deno version 1.11.4. 

See: https://github.com/cmorten/deno-rollup/issues/39

## Details

Upgraded to deno std@0.100.0 that it is compatible with deno version 1.11.4 and Test are now passing.

## CheckList

- [x] PR starts with [#_ISSUE_ID_].
- [x] Has been tested (where required).

### CODE REVIEW

**Review by cmorten — APPROVED** [review]

**Comment by cmorten** [comment]
Looks like hitting https://github.com/denoland/deno_std/issues/961, think we need to upgrade the CI to use latest Deno `1.11.4`.

**Comment by cmorten** [comment]
@eclosson do you mind update the GitHub workflows to use `1.11.4` as well so CI can pass? Sim. to what has been attempted in https://github.com/cmorten/deno-rollup/pull/38/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88

**Comment by eclosson** [comment]
Nope, working through it.

**Comment by eclosson** [comment]
@cmorten gihub action updated and looks like that did the trick. Let me know if there is anything else you'd like done.

**Pull request merged**
