### PR TITLE
feat: introduce plugins

### PR DESCRIPTION
**Pull request by cmorten**
# Issue

No issue.

## Details

- feat: add `html`, `image`, `json` and `yaml` plugins.
- docs: add examples for using plugins
- fix: handling 

## CheckList

- [ ] PR starts with [#_ISSUE_ID_].
- [ ] Has been tested (where required).

### CODE REVIEW

**Comment by probins** [comment]
interesting. I've not used the plugins this is based on, but a couple of quick points:

1. implementation of import assertions in v8 is nearing completion https://bugs.chromium.org/p/v8/issues/detail?id=10958&q=import%20assertions&can=2 which should be available in Deno soon after. JSON modules should follow soon after that https://bugs.chromium.org/p/v8/issues/detail?id=11189&q=json%20module&can=2. This means that JSON files can be imported natively as a module. CSS should follow after that, though HTML may take longer. I would suggest going with that rather than using a non-native method.
2. I was going to suggest a rewrite for the Readme Overview section, which currently says deno-rollup is "to bundle Deno code". Particularly if you're bundling HTML, this is aimed at browsers, not Deno. I'd suggest changing and expanding this Readme section

**Comment by cmorten** [comment]
> interesting. I've not used the plugins this is based on, but a couple of quick points:
> 
>     1. implementation of import assertions in v8 is nearing completion https://bugs.chromium.org/p/v8/issues/detail?id=10958&q=import%20assertions&can=2 which should be available in Deno soon after. JSON modules should follow soon after that https://bugs.chromium.org/p/v8/issues/detail?id=11189&q=json%20module&can=2. This means that JSON files can be imported natively as a module. CSS should follow after that, though HTML may take longer. I would suggest going with that rather than using a non-native method.
> 
>     2. I was going to suggest a rewrite for the Readme Overview section, which currently says deno-rollup is "to bundle Deno code". Particularly if you're bundling HTML, this is aimed at browsers, not Deno. I'd suggest changing and expanding this Readme section

The purpose of these plugins is to provide a thin layer for common, and indeed official, Rollup plugins to help enable front-end development.

I'm very excited for JSON modules (import assertions and all the rest that is on it's way), and very much hope that folks would opt to use the native capabilities over this plugin once it drops! Until then however, this provides a small stopgap to provide like-for-like with current Rollup on Node.

Good point r.e. "Deno code" - it is a bundler running on Deno that can bundle Deno code, but also browser code (and in theory anything else provided you have the appropriate plugin!). I will adjust it to be slightly broader - if you have a good idea for a tagline / readme update then please do submit a PR 😄

**Comment by cmorten** [comment]
Gone with "modules" over "Deno code" in the README for now as that is how it's described in the official Rollup lib - <https://github.com/rollup/rollup#overview>

**Comment by probins** [comment]
ok. In the readme, I would say that it can bundle both JS and TS, and expand on how it differs from standard Rollup. But, as you say, I can always submit a PR.

**Pull request merged**
